### PR TITLE
Blockly Core v5

### PR DESCRIPTION
**Pull request by AmbientOSX**
Makes disabled blocks more visibly disabled - removes some dropdown categories and adds back comments category.

@kadst43 @BrettASwift

### CODE REVIEW

**Comment by kadst43** [comment]
:+1:

**Comment by kadst43** [comment]
Though it's unfortunate that this has to be done in the core.

**Comment by AmbientOSX** [comment]
Alternative is to use block hues as an indicator. Might also be possible to
hijack the CSS on our side?

**Comment by kadst43** [comment]
For the short run, let's leave it as is.  Down the road, you may want to think about how to expose Blockly settings like this to the application, so that each VWF application can set them differently.

**Pull request merged**
