### PR TITLE
[WIP] Branch/mg staging+dev

### PR DESCRIPTION
**Pull request by BrettASwift**
WORK IN PROGRESS --- DO NOT MERGE

@kadst43 @AmbientOSX 

This is the branch I'm using to bring mars-game up to development. I want to keep track of the changes and any discussion on where to go with this branch can happen here. Right now, this should be used along with https://github.com/virtual-world-framework/mars-game/pull/485 for testing.

### CODE REVIEW

**Comment by BrettASwift** [comment]
@scottnc27603 Hey Scott. I'm seeing the shadow issue with the directional light target not working. Is there a workaround for that in threejs? Also, in Mars-Game, there's an issue with alpha on the tire tracks running through the canyon.

**Comment by BrettASwift** [comment]
Fixed the light target issue.

**Comment by scottnc27603** [comment]
Oh, sorry, I just saw this.  Where was the fix?  I know we had seen that
the first time we tried to go to threejs r69.

Scott

**Comment by BrettASwift** [comment]
https://github.com/virtual-world-framework/vwf/commit/9a69f5bf76d6cf7a09b595123a2eae6300d4f6ff

This commit fixes it. You have to update the target matrix now. It was auto-updating before.

**Comment by BrettASwift** [comment]
@AmbientOSX @kadst43 Rebased on mars-game-staging and development. If using this branch, update your local version.

**Comment by BrettASwift** [comment]
Closing this. Nothing to see here.

**Pull request closed without merging**
