### PR TITLE
Prints more detail when we run into a YAML parse error

### PR DESCRIPTION
**Pull request by nmarshak1337**
Not sure if the pull request should be to mars-game-staging or to somewhere else.

### CODE REVIEW

**Comment by davideaster** [comment]
Looks good.

Before merging, maybe take a look at `exceptionMessage` in `support/client/lib/vwf/utility.js` to see if that could help with formatting.

**Comment by nmarshak1337** [comment]
support/client/lib/vwf/utility.js looks useful, but how do I use it in the node server? I believe utility.js is an AMD module, which means that we’ll need to make the require.js node module a dependency. Then utility.js has more dependencies inside VWF.

I could do the above, but I hesitate because it seems heavy-handed for what I want to do. Any thoughts?

Pull request closed until I push more code / am ready to merge.

**Comment by davideaster** [comment]
You would need to copy it. That's not ideal of course, but browser libraries and node libraries tend to use different module schemes. The client's utility library isn't a separate package right now eight even though it is a standalone module.

**Comment by nmarshak1337** [comment]
Merged! 

`exceptionMessage` in `support/client/lib/vwf/utility.js` doesn't seem to help here, as much as I would have liked to use it  that function seems to be used for handling a client-side error. In node there's no window, the error doesn't seem to have a stack, and there's no toString method. It's good to know about for future reference though.

**Pull request merged**
