### PR TITLE
Mars Game Optimization Tests

### PR DESCRIPTION
**Pull request by AmbientOSX**
@kadst43 @BrettASwift @davideaster 

Seeing some new errors/warnings... notably:

(ERROR) Unsupported light type for shadowrender @ three.js:25381

(WARNING) @ three.js:24586 THREE.WebGLProgram: gl.getProgramInfoLog() (90,7-102): warning X3557: loop only executes for 1 iteration(s), forcing loop to unroll
(117,7-102): warning X3557: loop only executes for 1 iteration(s), forcing loop to unroll

(WARNING) @ three.js:24586 THREE.WebGLProgram: gl.getProgramInfoLog() (88,7-102): warning X3557: loop only executes for 1 iteration(s), forcing loop to unroll
(108,7-102): warning X3557: loop only executes for 1 iteration(s), forcing loop to unroll

(WARNING) @ localhost/:1 [.WebGLRenderingContext-00000000054A98E0]GL ERROR :GL_INVALID_OPERATION : glDrawElements: range out of bounds for buffer (x 256)

...

That said, load times seem drastically improved and two rovers executing at once is feasible. Still some slowdown over time / with 3 executing at once. Camera movement seems smoother. Thanks to David for changes.

### CODE REVIEW

**Comment by kadst43** [comment]
Are we sure those are new with David's changes?  Or were they introduced with some of Brett's shader changes recently?

**Comment by kadst43** [comment]
(In any case, :+1:.  Let's get it in so we can start testing with it)

**Comment by davideaster** [comment]
Odd. I can't think of how this might break WebGL. Maybe it's related to the threes.js changes where properties are pulled up from the prototypes.

**Comment by AmbientOSX** [comment]
Dont think we've merged in the shader changes yet - Ive seen the "loop unroll" error intermittently before but never the shadow/GL Errors... anyway - merging

**Comment by kadst43** [comment]
Shader changes are definitely merged - at least some of them are.  The video of the animated shader that's up on Redmine was made in mars-game-development.

**Comment by AmbientOSX** [comment]
Ah ok - was just looking at the open PR :)

**Pull request merged**
