### PR TITLE
Branch/optimized private properties

### PR DESCRIPTION
**Pull request by AmbientOSX**
Changes for testing property$ behavior of treating those properties as private record values for mars-game optimization. Supporting changes: https://github.com/virtual-world-framework/mars-game/pull/513

### CODE REVIEW

**Comment by BrettASwift** [comment]
Looks like this needs to be rebased. I can't really tell what's going on here until it is.

**Comment by AmbientOSX** [comment]
@BrettASwift Yep - sorry - done

**Comment by eric79** [comment]
I love the changes in the `threejs` driver.  If those were in a separate branch, I would recommend merging that to `development` and everywhere else that you wanted it immediately.

As for the `property$` changes ... have you tested them to see if they make a performance difference for you?  There are a couple of things about that change:
1. You cannot add setters and getters for those properties (since the javascript driver is being skipped).
2. This would not be able to be merged back into `development` unless some extensive documentation explained why `property$` properties are different than others.
3. I would have to spend more time looking at how `property$` properties are treated to make sure that they don't break the kernel re-entry flow.  @davideaster, if you're confident that it does what it needs to, then I will trust you.  But since that piece of code is deceptively complex, it would take me a while to wrap my mind around it again to make sure that it was doing the right things in the 'else`.

If they don't make a performance difference then we shouldn't do this.

**Comment by kadst43** [comment]
Merging (into mars-game-development only).  It may not be "all the way" ready, but it doesn't seem to break anything and does help performance - which we need right now.  I'll leave the branch open (for now) in case we want to make more changes.

**Pull request merged**
